repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^md2zhihu/_vendor/
      - id: ruff-format
        exclude: ^md2zhihu/_vendor/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--follow-imports=silent, --ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
        files: ^md2zhihu/
        exclude: ^md2zhihu/_vendor/
